ok_add_library(VisorVR-Events STATIC Events.cpp)
target_link_libraries(
  VisorVR-Events
  PUBLIC
  VisorVR-config
  VisorVR-dprint
  VisorVR-task
  ThirdParty::WIL
  ThirdParty::CppWinRT
  ThirdParty::bindline
  PRIVATE
  VisorVR-config
  VisorVR-fatal
)
target_include_directories(VisorVR-Events PUBLIC "${CMAKE_CURRENT_SOURCE_DIR}/include")

include(PDFNavigation.cmake)
include(SteamVRKneeboard.cmake)

ok_add_library(
  VisorVR-ChromiumApp
  STATIC
  ChromiumApp.cpp
  include/VisorVR/ChromiumApp.hpp
)
target_link_libraries(
  VisorVR-ChromiumApp
  PUBLIC
  Cef::LibCef
  PRIVATE
  VisorVR-DXResources
  VisorVR-Filesystem
  VisorVR-dprint
  VisorVR-version
)
target_include_directories(
  VisorVR-ChromiumApp
  PUBLIC
  "${CMAKE_CURRENT_SOURCE_DIR}/include"
)

ok_add_library(
  VisorVR-ChromiumWorker
  STATIC
  ChromiumWorker.cpp
  include/VisorVR/ChromiumWorker.hpp
)
target_link_libraries(
  VisorVR-ChromiumWorker
  PUBLIC
  Cef::LibCef
  VisorVR-JS-Sources
  # Be *very* wary of adding anything else, and make sure
  # to test in release mode.
  #
  # In release mode, make sure that `chrome://sandbox` shows that renderer
  # processes are sandboxed
)
target_include_directories(
  VisorVR-ChromiumWorker
  PUBLIC
  "${CMAKE_CURRENT_SOURCE_DIR}/include"
)

ok_add_library(
  VisorVR-App-Common
  STATIC
  APIEventServer.cpp
  AppSettings.cpp
  CachedLayer.cpp
  Coordinates.cpp
  CursorRenderer.cpp
  DCSExtractedMission.cpp
  DCSGrid.cpp
  DCSMagneticModel.cpp
  DebugPrivileges.cpp
  DoodleRenderer.cpp
  DoodleSettings.cpp
  FilesystemWatcher.cpp
  IHasDebugInformation.cpp
  InterprocessRenderer.cpp
  KneeboardState.cpp
  KneeboardView.cpp
  LaunchURI.cpp
  Lua.cpp
  OpenXRMode.cpp
  PageSource/ChromiumPageSource.cpp
  PageSource/ChromiumPageSource_Client.cpp
  PageSource/ChromiumPageSource_Client.hpp
  PageSource/ChromiumPageSource_RenderHandler.cpp
  PageSource/ChromiumPageSource_RenderHandler.hpp
  PageSource/FileHash.cpp
  PageSource/FilePageSource.cpp
  PageSource/FolderPageSource.cpp
  PageSource/HWNDPageSource.cpp
  PageSource/IPageSource.cpp
  PageSource/ImageFilePageSource.cpp
  PageSource/PDFFilePageSource.cpp
  PageSource/PageSourceWithDelegates.cpp
  PageSource/PlainTextFilePageSource.cpp
  PageSource/PlainTextPageSource.cpp
  PageSource/include/VisorVR/ChromiumPageSource.hpp
  PageSource/include/VisorVR/FileHash.hpp
  PageSource/include/VisorVR/FilePageSource.hpp
  PageSource/include/VisorVR/FolderPageSource.hpp
  PageSource/include/VisorVR/HWNDPageSource.hpp
  PageSource/include/VisorVR/IPageSource.hpp
  PageSource/include/VisorVR/IPageSourceWithCursorEvents.hpp
  PageSource/include/VisorVR/IPageSourceWithDeveloperTools.hpp
  PageSource/include/VisorVR/IPageSourceWithInternalCaching.hpp
  PageSource/include/VisorVR/IPageSourceWithNavigation.hpp
  PageSource/include/VisorVR/ImageFilePageSource.hpp
  PageSource/include/VisorVR/PDFFilePageSource.hpp
  PageSource/include/VisorVR/PageSourceWithDelegates.hpp
  PageSource/include/VisorVR/PlainTextFilePageSource.hpp
  PageSource/include/VisorVR/PlainTextPageSource.hpp
  Plugin.cpp
  PluginStore.cpp
  ProcessShutdownBlock.cpp
  ProfileSettings.cpp
  RenderTarget.cpp
  RunSubprocessAsync.cpp
  RunnerThread.cpp
  Settings.cpp
  Tab/BrowserTab.cpp
  Tab/DCSAircraftTab.cpp
  Tab/DCSBriefingTab.cpp
  Tab/DCSBriefingTab_sections.cpp
  Tab/DCSMissionTab.cpp
  Tab/DCSRadioLogTab.cpp
  Tab/DCSTab.cpp
  Tab/DCSTerrainTab.cpp
  Tab/EndlessNotebookTab.cpp
  Tab/FolderTab.cpp
  Tab/NavigationTab.cpp
  Tab/PluginTab.cpp
  Tab/SingleFileTab.cpp
  Tab/TabBase.cpp
  Tab/WindowCaptureTab.cpp
  Tab/include/VisorVR/BrowserTab.hpp
  Tab/include/VisorVR/CursorEvent.hpp
  Tab/include/VisorVR/DCSAircraftTab.hpp
  Tab/include/VisorVR/DCSBriefingTab.hpp
  Tab/include/VisorVR/DCSMissionTab.hpp
  Tab/include/VisorVR/DCSRadioLogTab.hpp
  Tab/include/VisorVR/DCSTab.hpp
  Tab/include/VisorVR/DCSTerrainTab.hpp
  Tab/include/VisorVR/EndlessNotebookTab.hpp
  Tab/include/VisorVR/FolderTab.hpp
  Tab/include/VisorVR/ITab.hpp
  Tab/include/VisorVR/ITabWithSettings.hpp
  Tab/include/VisorVR/NavigationTab.hpp
  Tab/include/VisorVR/PluginTab.hpp
  Tab/include/VisorVR/SingleFileTab.hpp
  Tab/include/VisorVR/TabBase.hpp
  Tab/include/VisorVR/WindowCaptureTab.hpp
  TabView.cpp
  TabsList/TabsList.cpp
  TabsList/include/VisorVR/TabTypes.hpp
  TabsList/include/VisorVR/TabsList.hpp
  TextSettings.cpp
  ToolbarItems/ClearUserInputAction.cpp
  ToolbarItems/CreateTabActions.cpp
  ToolbarItems/IToolbarItem.cpp
  ToolbarItems/NextTabAction.cpp
  ToolbarItems/PreviousTabAction.cpp
  ToolbarItems/ReloadTabAction.cpp
  ToolbarItems/SwitchProfileAction.cpp
  ToolbarItems/SwitchProfileFlyout.cpp
  ToolbarItems/SwitchTabAction.cpp
  ToolbarItems/SwitchTabFlyout.cpp
  ToolbarItems/TabDeveloperToolsAction.cpp
  ToolbarItems/TabFirstPageAction.cpp
  ToolbarItems/TabNavigationAction.cpp
  ToolbarItems/TabNextPageAction.cpp
  ToolbarItems/TabPreviousPageAction.cpp
  ToolbarItems/ToggleBookmarkAction.cpp
  ToolbarItems/ToolbarAction.cpp
  ToolbarItems/ToolbarFlyout.cpp
  ToolbarItems/ToolbarSeparator.cpp
  ToolbarItems/ToolbarToggleAction.cpp
  ToolbarItems/include/VisorVR/ClearUserInputAction.hpp
  ToolbarItems/include/VisorVR/CreateTabActions.hpp
  ToolbarItems/include/VisorVR/ICheckableToolbarItem.hpp
  ToolbarItems/include/VisorVR/ISelectableToolbarItem.hpp
  ToolbarItems/include/VisorVR/IToolbarFlyout.hpp
  ToolbarItems/include/VisorVR/IToolbarItem.hpp
  ToolbarItems/include/VisorVR/IToolbarItemWithConfirmation.hpp
  ToolbarItems/include/VisorVR/IToolbarItemWithVisibility.hpp
  ToolbarItems/include/VisorVR/NextTabAction.hpp
  ToolbarItems/include/VisorVR/PreviousTabAction.hpp
  ToolbarItems/include/VisorVR/ReloadTabAction.hpp
  ToolbarItems/include/VisorVR/SwitchProfileAction.hpp
  ToolbarItems/include/VisorVR/SwitchProfileFlyout.hpp
  ToolbarItems/include/VisorVR/SwitchTabAction.hpp
  ToolbarItems/include/VisorVR/SwitchTabFlyout.hpp
  ToolbarItems/include/VisorVR/TabDeveloperToolsAction.hpp
  ToolbarItems/include/VisorVR/TabFirstPageAction.hpp
  ToolbarItems/include/VisorVR/TabNavigationAction.hpp
  ToolbarItems/include/VisorVR/TabNextPageAction.hpp
  ToolbarItems/include/VisorVR/TabPreviousPageAction.hpp
  ToolbarItems/include/VisorVR/ToggleBookmarkAction.hpp
  ToolbarItems/include/VisorVR/ToolbarAction.hpp
  ToolbarItems/include/VisorVR/ToolbarFlyout.hpp
  ToolbarItems/include/VisorVR/ToolbarSeparator.hpp
  ToolbarItems/include/VisorVR/ToolbarToggleAction.hpp
  TroubleshootingStore.cpp
  UILayers/BookmarksUILayer.cpp
  UILayers/ConfirmationUILayer.cpp
  UILayers/FlyoutMenuUILayer.cpp
  UILayers/FooterUILayer.cpp
  UILayers/HeaderUILayer.cpp
  UILayers/IUILayer.cpp
  UILayers/TabViewUILayer.cpp
  UILayers/UILayerBase.cpp
  UILayers/include/VisorVR/BookmarksUILayer.hpp
  UILayers/include/VisorVR/ConfirmationUILayer.hpp
  UILayers/include/VisorVR/FlyoutMenuUILayer.hpp
  UILayers/include/VisorVR/FooterUILayer.hpp
  UILayers/include/VisorVR/HeaderUILayer.hpp
  UILayers/include/VisorVR/IUILayer.hpp
  UILayers/include/VisorVR/TabViewUILayer.hpp
  UILayers/include/VisorVR/UILayerBase.hpp
  UISettings.cpp
  UserActionHandler.cpp
  UserInput/DirectInputAdapter.cpp
  UserInput/DirectInputDevice.cpp
  UserInput/DirectInputJoystickListener.cpp
  UserInput/DirectInputKeyboardListener.cpp
  UserInput/DirectInputListener.cpp
  UserInput/DirectInputMouseListener.cpp
  UserInput/DirectInputSettings.cpp
  UserInput/GetDirectInputDevices.cpp
  UserInput/OTDIPCClient.cpp
  UserInput/TabletInputAdapter.cpp
  UserInput/TabletInputDevice.cpp
  UserInput/TabletSettings.cpp
  UserInput/UserInputButtonBinding.cpp
  UserInput/UserInputButtonEvent.cpp
  UserInput/UserInputDevice.cpp
  UserInput/include/VisorVR/CursorClickableRegions.hpp
  UserInput/include/VisorVR/DirectInputAdapter.hpp
  UserInput/include/VisorVR/DirectInputDevice.hpp
  UserInput/include/VisorVR/DirectInputJoystickListener.hpp
  UserInput/include/VisorVR/DirectInputKeyboardListener.hpp
  UserInput/include/VisorVR/DirectInputListener.hpp
  UserInput/include/VisorVR/DirectInputMouseListener.hpp
  UserInput/include/VisorVR/DirectInputSettings.hpp
  UserInput/include/VisorVR/GetDirectInputDevices.hpp
  UserInput/include/VisorVR/OTDIPCClient.hpp
  UserInput/include/VisorVR/TabletInputAdapter.hpp
  UserInput/include/VisorVR/TabletInputDevice.hpp
  UserInput/include/VisorVR/TabletSettings.hpp
  UserInput/include/VisorVR/UserInputButtonBinding.hpp
  UserInput/include/VisorVR/UserInputButtonEvent.hpp
  UserInput/include/VisorVR/UserInputDevice.hpp
  VRSettings.cpp
  ViewsSettings.cpp
  WGCRenderer.cpp
  include/VisorVR/APIEventServer.hpp
  include/VisorVR/AppSettings.hpp
  include/VisorVR/Bookmark.hpp
  include/VisorVR/CachedLayer.hpp
  include/VisorVR/Coordinates.hpp
  include/VisorVR/CursorRenderer.hpp
  include/VisorVR/DCSExtractedMission.hpp
  include/VisorVR/DCSEvents.hpp
  include/VisorVR/DCSGrid.hpp
  include/VisorVR/DCSMagneticModel.hpp
  include/VisorVR/DebugPrivileges.hpp
  include/VisorVR/DoodleRenderer.hpp
  include/VisorVR/DoodleSettings.hpp
  include/VisorVR/FilesystemWatcher.hpp
  include/VisorVR/IHasDebugInformation.hpp
  include/VisorVR/IHasDisposeAsync.hpp
  include/VisorVR/InterprocessRenderer.hpp
  include/VisorVR/KneeboardState.hpp
  include/VisorVR/KneeboardView.hpp
  include/VisorVR/KneeboardViewID.hpp
  include/VisorVR/LaunchURI.hpp
  include/VisorVR/Lua.hpp
  include/VisorVR/OpenXRMode.hpp
  include/VisorVR/Plugin.hpp
  include/VisorVR/PluginStore.hpp
  include/VisorVR/ProcessShutdownBlock.hpp
  include/VisorVR/ProfileSettings.hpp
  include/VisorVR/Registry.hpp
  include/VisorVR/RenderTarget.hpp
  include/VisorVR/RenderTargetID.hpp
  include/VisorVR/RunSubprocessAsync.hpp
  include/VisorVR/RunnerThread.hpp
  include/VisorVR/Settings.hpp
  include/VisorVR/TabView.hpp
  include/VisorVR/TextSettings.hpp
  include/VisorVR/TroubleshootingStore.hpp
  include/VisorVR/TryEnqueue.hpp
  include/VisorVR/UISettings.hpp
  include/VisorVR/UniqueID.hpp
  include/VisorVR/UserActionHandler.hpp
  include/VisorVR/ViewsSettings.hpp
  include/VisorVR/WGCRenderer.hpp
  include/VisorVR/WebPageSourceKind.hpp
  include/VisorVR/WebPageSourceSettings.hpp
  include/VisorVR/bindline.hpp
  include/VisorVR/cppwinrt.hpp
  include/VisorVR/enable_shared_from_this.hpp
  include/VisorVR/final_release_deleter.hpp
  include/VisorVR/weak_refs.hpp
)
target_compile_definitions(
  VisorVR-App-Common
  PUBLIC
  "DIRECTINPUT_VERSION=0x0800"
)
target_link_libraries(
  VisorVR-App-Common
  PUBLIC
  VisorVR-Events
  VisorVR-StateMachine
  ThirdParty::DirectXTK
  ThirdParty::JSON
  Cef::LibCef
  PRIVATE
  VisorVR-D2DErrorRenderer
  VisorVR-DXResources
  VisorVR-Filesystem
  VisorVR-APIEvent
  VisorVR-EnumerateProcesses
  VisorVR-GetSystemColor
  VisorVR-PDFNavigation
  VisorVR-RayIntersectsRect
  VisorVR-RuntimeFiles
  VisorVR-SHM
  VisorVR-SteamVRKneeboard
  VisorVR-ThreadGuard
  VisorVR-UTF8
  VisorVR-WindowCaptureControl
  VisorVR-config
  VisorVR-dprint
  VisorVR-fatal
  VisorVR-handles
  VisorVR-scope_exit
  VisorVR-semver
  VisorVR-task
  System::D2d1
  System::Dinput8
  System::Dwmapi
  System::Dxguid
  System::Rpcrt4
  System::Wtsapi32
  ThirdParty::GeographicLib
  ThirdParty::LibZip
  ThirdParty::Lua::DelayLoad
  ThirdParty::OTDIPC
  ThirdParty::OpenVR
  ThirdParty::WMM
  ThirdParty::magic_json_serialize_enum
)

target_include_directories(
  VisorVR-App-Common
  PUBLIC
  ${CMAKE_CURRENT_SOURCE_DIR}/PageSource/include
  ${CMAKE_CURRENT_SOURCE_DIR}/Tab/include
  ${CMAKE_CURRENT_SOURCE_DIR}/TabsList/include
  ${CMAKE_CURRENT_SOURCE_DIR}/ToolbarItems/include
  ${CMAKE_CURRENT_SOURCE_DIR}/UILayers/include
  ${CMAKE_CURRENT_SOURCE_DIR}/UserInput/include
  ${CMAKE_CURRENT_SOURCE_DIR}/include
)

target_link_windows_app_sdk(VisorVR-App-Common)

ok_add_library(VisorVR::App::Common ALIAS VisorVR-App-Common)