ok_add_library(VisorVR-PDFNavigation STATIC PDFNavigation.cpp)
target_link_libraries(
  VisorVR-PDFNavigation
  PUBLIC
  VisorVR-Lib-Headers
  VisorVR-shims
)
target_link_libraries(
  VisorVR-PDFNavigation
  PRIVATE
  VisorVR-DebugTimer
  VisorVR-UTF8
  VisorVR-dprint
  ThirdParty::QPDF
)
target_include_directories(
  VisorVR-PDFNavigation
  PUBLIC
  "${CMAKE_CURRENT_SOURCE_DIR}/include"
)
