ok_add_library(
  VisorVR-SteamVRKneeboard
  STATIC
  SteamVRKneeboard.cpp
)
target_link_libraries(
  VisorVR-SteamVRKneeboard
  PUBLIC
  VisorVR-DXResources
  VisorVR-D3D11
  VisorVR-SHM-Client-D3D11
  VisorVR-VRKneeboard
  VisorVR-config
  ThirdParty::DirectXTK
  ThirdParty::OpenVR
  VisorVR-Lib-Headers
)
target_link_libraries(
  VisorVR-SteamVRKneeboard
  PRIVATE
  VisorVR-dprint
  VisorVR-EnumerateProcesses
)
target_include_directories(
  VisorVR-SteamVRKneeboard
  PUBLIC
  "${CMAKE_CURRENT_SOURCE_DIR}/include"
)